medGet/Controllers/BulkAddController.cs
using CsvHelper;
using CsvHelper.Configuration;
using medGet.Database;
using medGet.Models;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;

namespace medGet.Controllers
{
    public class BulkAddController : Controller
    {
        private readonly ApplicationDbContext _db;

        public BulkAddController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<MedicineDetails> objList = _db.MedicineDetails
                .Take(10);
            return View(objList);
        }

        [HttpPost]
        public IActionResult Index(string text)
        {
            if (!String.IsNullOrEmpty(text))
            {
                IEnumerable<MedicineDetails> objList = _db.MedicineDetails
                    .Where(p => (p.BrandName.Contains(text)
                            || p.CompanyName.Contains(text)
                            || p.DAR.Contains(text)
                            || p.Generic.Contains(text))
                            && !p.Price.Contains("0"));
                return View(objList);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        public IActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Insert(String Path)
        {
            var config = new CsvConfiguration(CultureInfo.InvariantCulture)
            {
                HeaderValidated = null,
                MissingFieldFound = null
            };
            using (var streamReader = new StreamReader(Path))
            {
                using var csvReader = new CsvReader(streamReader, config);
                csvReader.Context.RegisterClassMap<MedicineDetailsMap>();
                var records = csvReader.GetRecords<MedicineDetails>().ToList();
                _db.MedicineDetails.AddRange(records);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public class MedicineDetailsMap : ClassMap<MedicineDetails>
        {
            public MedicineDetailsMap()
            {
                Map(m => m.CompanyName).Name("name").ToString();
                Map(m => m.BrandName).Name("brand").ToString();
                Map(m => m.Generic).Name("generic").ToString();
                Map(m => m.Strength).Name("strength").ToString();
                Map(m => m.Dosages).Name("dosages").ToString();
                Map(m => m.Price).Name("price").ToString();
                Map(m => m.UsedFor).Name("usedfor").ToString();
                Map(m => m.DAR).Name("dar").ToString();
            }
        }
    }
}

medGet/Views/BulkAdd/Index.cshtml
@model IEnumerable<medGet.Models.MedicineDetails>
@{
    ViewData["Title"] = "Add Medicine Data";
}

    <div class="text-center">
        <div>
        <h4 scope="col">Update Medicine Data</h4>
        <a type="button" class="btn btn-info text-white" href="">Update Medicine Data</a>
        </div>
        <hr />
    </div>

    <form class="d-flex" asp-controller="BulkAdd" asp-action="Index" method="post">
            <input class="form-control me-sm-2" type="text" name="text" id="text" placeholder="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit" value="Index">Search</button>
    </form>
<hr />

    <table class="table table-hover">
        <thead>
            <tr>
                @*<th scope="col">Id</th>*@
                <th scope="col">Company</th>
                <th scope="col">Brand</th>
                <th scope="col">Generic</th>
                <th scope="col">Strength</th>
                <th scope="col">Type</th>
                <th scope="col">Price</th>
                <th scope="col">Used For</th>
                <th scope="col">DAR No.</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                if (item.UsedFor.Equals("R"))
                {
                    <tr class="table-secondary">
                        @*<th scope="row">@item.Id</th>*@
                        <td>@item.CompanyName</td>
                        <td>@item.BrandName</td>
                        <td>@item.Generic</td>
                        <td>@item.Strength</td>
                        <td>@item.Dosages</td>
                        <td>@item.Price</td>
                        <td>@item.UsedFor</td>
                        <td>@item.DAR</td>
                    </tr>
                }
                if (item.UsedFor.Equals("Human"))
                {
                    <tr class="table-info">
                        @*<th scope="row">@item.Id</th>*@
                        <td>@item.CompanyName</td>
                        <td>@item.BrandName</td>
                        <td>@item.Generic</td>
                        <td>@item.Strength</td>
                        <td>@item.Dosages</td>
                        <td>@item.Price</td>
                        <td>@item.UsedFor</td>
                        <td>@item.DAR</td>
                    </tr>
                }
                if (item.UsedFor.Equals("Veterinary"))
                {
                    <tr class="table-warning">
                        @*<th scope="row">@item.Id</th>*@
                        <td>@item.CompanyName</td>
                        <td>@item.BrandName</td>
                        <td>@item.Generic</td>
                        <td>@item.Strength</td>
                        <td>@item.Dosages</td>
                        <td>@item.Price</td>
                        <td>@item.UsedFor</td>
                        <td>@item.DAR</td>
                    </tr>
                }
            }
        </tbody>
    </table>